### ISSUE TITLE
例子看不太懂

### ISSUE THREAD

**Issue by Edelweiss-Snow** [lesismal/nbio-examples#10]
![image](https://github.com/lesismal/nbio-examples/assets/32295371/85aa6495-08a7-4648-9550-20ab52a85af5)
请问这个里面的readMessage这个函数现在是在哪里的，我看貌似现在只有read了，但是我还找不到nbhttp.NewParser()这个如何使用

**Comment by lesismal** [comment]
nbhttp.NewParser() 通常不需要用户自己调用，除非想自己封装协议解析。

这个库里的例子不只是nbio自己的用法，也有一些对比其他库，截图里的ReadMessage应该不是nbio，可以看下源码中import的是哪个库、比如gorilla

**Comment by Edelweiss-Snow** [comment]
> nbhttp.NewParser() 通常不需要用户自己调用，除非想自己封装协议解析。
> 
> 这个库里的例子不只是nbio自己的用法，也有一些对比其他库，截图里的ReadMessage应该不是nbio，可以看下源码中import的是哪个库、比如gorilla

请问这个nbio的连接收发消息的例子在哪里呢，我看到了那个read方法，但是搞不太懂怎么使用

**Comment by lesismal** [comment]
nbio readme里有一些例子链接，可以先看那里。特别基础的问题先自己研究下才好提高

**Comment by Edelweiss-Snow** [comment]
> nbio readme里有一些例子链接，可以先看那里。特别基础的问题先自己研究下才好提高

好的我再看看，谢谢
