### ISSUE TITLE
[help] onOpen, onMessage, and onClose not executed

### ISSUE THREAD

**Issue by BigBoulard** [lesismal/nbio-examples#11]
Hi,

First off, there's no bug, I just struggle to make it work. I implemented a solution using Gorilla but I want to try other options. I started from this example <https://github.com/lesismal/nbio-examples/blob/master/websocket/server/server.go>.
The connection is upgraded and I can write to it but the `onOpen`, `onMessage`, and `onClose` handlers are not executed I don't know why.
If you could give me a hand that would be much appreciated :)

```go
import( "github.com/lesismal/nbio/nbhttp/websocket" )

type WSClient struct {
   upgrader *websocket.Upgrader
   ws       *websocket.Conn
   ...
}

func NewWSClient(...) error(
  c := &WSClient{
		upgrader:    websocket.NewUpgrader(),
		...
  }
  
  // creates the ws
  conn, err := c.Upgrade(ginCtx.Writer, ginCtx.Request)
  if err != nil {
	return fmt.Errorf("c.Upgrade: can't upgrade connection: %w", err)
  }
  c.ws = conn
  
  // ws size limit
 conn.MessageLengthLimit = conf.MessageMaxSize
 
 c.upgrader.OnOpen(
    func(conn *websocket.Conn) {
	println(fmt.Sprintf("New connection from %s", conn.RemoteAddr().String()))
    },
 )
 
 c.upgrader.OnMessage(
	func(conn *websocket.Conn, messageType websocket.MessageType, data []byte) {
		println(fmt.Sprintf("New message from %s", conn.RemoteAddr().String()))
        },
)

c.upgrader.OnClose(
	func(conn *websocket.Conn, err error) {
        println("connection closed")
	},
)
}
```

Then, I realized it was required to switch the default HTTP Server with your `nbhttp.Server`. The thing is I'm running on SSL, so I stumble on this example: <https://github.com/lesismal/nbio-examples/blob/master/tls/server/server.go> (but maybe I should have looked there: <https://github.com/lesismal/nbio-examples/blob/master/websocket_tls/server/server.go>).

```go
// application layer
import (
  "github.com/lesismal/llib/std/crypto/tls"
  "github.com/gin-gonic/gin"
  "github.com/lesismal/nbio/nbhttp"
)

// load cert
cert, err = tls.LoadX509KeyPair(getSSLCertFilePath(), getSSLPrivateKeyFilePath())
if err != nil {
	log.Fatalf("can't load SSL files %s or %s: %v ", getSSLCertFilePath(), getSSLPrivateKeyFilePath(), err)
}

// setup Gin router
router = gin.New()

// setup http server
app.Server = nbhttp.NewServer(nbhttp.Config{
	Network: "tcp",
	AddrsTLS:   []string{fmt.Sprintf("%s:%s", conf.HTTPServer.Host, conf.HTTPServer.Port)},
	TLSConfig: &tls.Config{
		Certificates:       []tls.Certificate{conf.HTTPServer.Certificate}, 
		InsecureSkipVerify: true, // WARN remove in prod
	},
	Handler: router,
}, app.Router, nil)

// launch server
err := app.Server.Start()
if err != nil {
	log.Fatalf("nbio.Start failed: %v\n", err)
}
```

**Comment by lesismal** [comment]
The difference between using std http.Server and nbio/nbhttp.Engine is: nbio supports non-blocking IO interfaces and can manage millions of connections using only a few goroutines which helps to save a lot of memory usage and reduce the huge cpu cost for gc.

**Comment by BigBoulard** [comment]
> Hi @BigBoulard , thank you for your attention to nbio!
> 
> > onOpen, onMessage, and onClose not executed
> 
> You should set Upgrader's handler(OnOpen/OnMessage/OnClose) before you call Upgrader.Upgrade(...).
> 
> > Then, I realized it was required to switch the default HTTP Server with your nbhttp.Server.
> 
> `nbio/nbhttp/websocket` can also be used to std http.Server, including http.Server over TLS(if start the server by LisenAndServeTLS): https://github.com/lesismal/nbio#using-websocket-with-std-server

Man, I'm sorry how I overlooked your example, thank you.

**Comment by lesismal** [comment]
You are welcome!
