### ISSUE TITLE
ping/pong process: idiomatic code WriteMessage vs WriteFrame

### ISSUE THREAD

**Issue by BigBoulard** [lesismal/nbio-examples#12]
Hi,

I've created a simple function to create a WS and it is working properly thanks to your advice.

The only thing I don't find in the examples is a pattern to implement the PING PONG procedure to check whether a web socket is idle.

So, I've created the following code that is working works, but there are 2 things:

- I've found that there's a `WriteFrame` method. I can guess that this one is intended to send PING, PONG, and CLOSE frames so it's probably better to use it than using `WriteMessage` to send PING frames but I don't understand all the `sendOpcode` and `fin` arguments. Plus, I don't really know what's the purpose of data cause I thought that the frame was identified by its type.

```go
func (*websocket.Conn).WriteFrame(messageType websocket.MessageType, sendOpcode bool, fin bool, data []byte) error
```

- I don't know if the way I've implemented the ping/pong process is how you think it should be done considering `nbio` capabilities.

I also have a doubt about the necessity to implement this ping/pong process when the client is a stress test backend script because web sockets are never idle in this specific situation, but maybe there's some timeout somewhere that may close the web socket I don't know.

Many thanks.

code sample for interacting with a browser and checking the WS state
```go
func (c *WSClient) createWS(ginCtx *gin.Context) (*websocket.Conn, error) {
	// onOpen handler
	c.upgrader.OnOpen(
		func(conn *websocket.Conn) {
			log.Printf("New connection from %s", conn.RemoteAddr().String()))
			// do something ...
		},
	)

	// onMessage handler
	c.upgrader.OnMessage(
		func(conn *websocket.Conn, messageType websocket.MessageType, data []byte) {
			// do something ...
		},
	)

	// onClose handler
	c.upgrader.OnClose(
		func(conn *websocket.Conn, err error) {
			log.Println("WS is Closed")
			c.Close()
		},
	)

	// check the Origin if the connection is made from a browser
	c.upgrader.CheckOrigin = func(r *http.Request) bool {
			return isAllowedHost(r.Header.Get("Origin"))
	}
	
  // upgrade the connection
	conn, err := c.upgrader.Upgrade(ginCtx.Writer, ginCtx.Request, nil)
	if err != nil {
		return nil, fmt.Errorf("c.upgrader.Upgrade error: %w", err)
	}

	// set ws size limit
	conn.MessageLengthLimit = conf.MessageMaxSize

	// set read timeout on the WS. we need to receive a pong before now() + pongWait
	if err := conn.SetReadDeadline(time.Now().Add(pongWait)); err != nil {
		return nil, fmt.Errorf("conn.SetReadDeadline error: %w", err)
	}

	// launch the PING goroutine
	// Browsers that support WebSockets automatically respond with a PONG frame, it's a built-in feature
	go func() {
		// triggers a ping at given interval
		ticker := time.NewTicker(pingInterval)
		defer func() {
			ticker.Stop()
		}()

		for range ticker.C {
			// WORKS AS WELL: 
			// if err := conn.WriteMessage(websocket.PingMessage, []byte{}); err != nil {
			if err := conn.WriteFrame(websocket.PingMessage, true, true, []byte{}); err != nil {
				log.Errorf("conn.WriteFrame: Ping attempt but WS closed: %w", err)
				return
			}
		}
	}()

	// SetPongHandler resets the READ deadline. see https://datatracker.ietf.org/doc/html/rfc6455#section-5.5.2
	conn.SetPongHandler(
		func (conn *websocket.Conn, msg string) {
			c.log.Debug("wsclient.pongHandler", "", "PONG")
			if err := conn.SetReadDeadline(time.Now().UTC().Add(pongWait)); err != nil {
				return nil, fmt.Errorf("SetReadDeadline error: %w", err)
			}
		},
	)

	return conn, nil
}
```

**Comment by lesismal** [comment]
> The only thing I don't find in the examples is a pattern to implement the PING PONG procedure to check whether a web socket is idle.

To send PING/PONG, you can use `wsConn.WriteMessage(websocket.PingMessage/PingMessage, data)`, just as you send `TextMessage/BinaryMessage`.

> I've found that there's a WriteFrame method. I can guess that this one is intended to send PING, PONG, and CLOSE frames so it's probably better to use it than using WriteMessage to send PING frames but I don't understand all the sendOpcode and fin arguments. Plus, I don't really know what's the purpose of data cause I thought that the frame was identified by its type.

`WriteFrame` is provided for users who want to control single frame size. The sendOpcode(only the first frame of a message need to send op code) and fin are used to pack the frame of `WebSocket protocol`, for more details, please refer to:
https://datatracker.ietf.org/doc/html/rfc6455#section-11.8
https://datatracker.ietf.org/doc/html/rfc6455#section-5.2

**Comment by lesismal** [comment]
> I also have a doubt about the necessity to implement this ping/pong process when the client is a stress test backend script because web sockets are never idle in this specific situation, but maybe there's some timeout somewhere that may close the web socket I don't know.

Yes, that's a good opinion! We shouldn't waste our network to send no-needed data!
I found that many developers send `PING` messages by the server to check the clients' alive state, but that will server's resource.
I think the best way to implement keepalive/heartbeat is: 
1. The server side `SetReadDeadline` and updates the deadline everytime when the server receives a full Message
2. The client side sends `PING` after a `keepalive` period since the last Message sent(no matter what kind of message). But to simplify the client side logic, we can just send the `PING` at a fixed speed since it's not a very frequent operation.

For using nbio, we can just config the `KeepaliveTime` to implement the keepalive checking on server side:
```golang
func newUpgrader() *websocket.Upgrader {
	u := websocket.NewUpgrader()
	// set your keepalive time, then nbio will SetReadDeadline:
	//    https://github.com/lesismal/nbio/blob/master/nbhttp/websocket/upgrader.go#L522
	// and update the deadline automatically:
	//    https://github.com/lesismal/nbio/blob/master/nbhttp/websocket/conn.go#L181
	u.KeepaliveTime = time.Second * 30
	u.OnOpen(func(c *websocket.Conn) {
		fmt.Println("OnOpen:", c.RemoteAddr().String())
	})
	u.OnMessage(func(c *websocket.Conn, messageType websocket.MessageType, data []byte) {
		// echo
		fmt.Println("OnMessage:", messageType, string(data))
		c.WriteMessage(messageType, data)
	})
	u.OnClose(func(c *websocket.Conn, err error) {
		fmt.Println("OnClose:", c.RemoteAddr().String(), err)
	})
	return u
}
```

For the client side, nbio websocket doesn't provide a `Keepalive` method, but can easily implement it like this(another framework)
https://github.com/lesismal/arpc/blob/master/client.go#L122

**Comment by lesismal** [comment]
BTW, nbio websocket has some default message handler, for `PING` message, nbio response a `PONG` by default:
https://github.com/lesismal/nbio/blob/master/nbhttp/websocket/upgrader.go#L108

So, usually you don't need to set a ping handler yourself.

**Comment by lesismal** [comment]
> For the client side, nbio websocket doesn't provide a Keepalive method, but can easily implement it like this(another framework)
> https://github.com/lesismal/arpc/blob/master/client.go#L122

Please notice that there's no need to use a ticker and hold a goroutine persistently, using time.AfterFunc+recursion only needs the goroutine when sending the message and the goroutine will exit after the sending. But make sure to check the conn's state and stop the recursion calling when the conn is closed, then we avoid goroutine leak.
