### ISSUE TITLE
stress test

### ISSUE THREAD

**Issue by BigBoulard** [lesismal/nbio-examples#13]
Hi,

I'm working on a chat application in Go. There's no load balancer or message queue, this will be one of the next phases.
For now, I want to get an idea of how many web socket connections the system could handle on a single instance with `TLS`, and how much resource is needed in terms of CPU and RAM.

So, I've built a stress test script that sends a `WSS` request and then writes a message on this connection every X seconds.
The server just echoes the message that is not read by the client. I've built 2 servers: `nbio`, and `gorilla` for reference.
The server prints how many connections have been created every 100 connections.

p.s. I've made abstraction on the persistence layer, and put aside the manager for the sake of simplicity.

I'm testing on `docker desktop` on `macOS` (`M2` > `arm64`) and `Compose`.

I've tested using `nbhttp.NewEngine`, `nbhttp.NewServer` and `nbio.newGopher` but I don't see a significant difference, but it is probably normal because I didn't 100% understand the difference between the 3.

I've created a repo so you can play with it:

<https://github.com/BigBoulard/go-chat-test>

Thank you so much.

**Comment by lesismal** [comment]
Here's a websocket benchmark repo:
https://github.com/lesismal/go-websocket-benchmark
related:
https://www.reddit.com/r/golang/comments/13wfae2/gowebsocketbenchmark_including_nbio/

nbio supports different IOMod for different scenarios, here's the explanation for different IOMod:
https://github.com/lesismal/nbio#different-iomod

If every single node of your service serves a huge number of connections, nbio with IOModNonBlocking would be a good choice, or using IOModMixed can gain a balance during different online periods. 


> I've tested using nbhttp.NewEngine, nbhttp.NewServer and nbio.newGopher but I don't see a significant difference, but it is probably normal because I didn't 100% understand the difference between the 3.

nbio.NewGopher and nbhttp.NewServer are old name in old versions, they are not deprecated is to keep compliant with old versions. nbio.NewEngine and nbhttp.NewEngine are just the same with the 2 types and are recommanded to be used.

**Comment by lesismal** [comment]
> I've created a repo so you can play with it:
> https://github.com/BigBoulard/go-chat-test

Thank you @BigBoulard , I will look into it when I am not busy.

**Comment by lesismal** [comment]
I just take a look at your repo.
If you want to test the server's ability, I think it's better to use the same gorilla client to test both servers.

**Comment by BigBoulard** [comment]
Do you see any drawback in the `nbio` part?
Which method should I be using between  `nbhttp.NewEngine`, `nbhttp.NewServer` and `nbio.newGopher`?

**Comment by lesismal** [comment]
nbhttp.NewEngine, nbhttp.NewServer : they are the same

nbio.newGopher: that's for 4th layer(TCP/UDP/Unix)

**Comment by BigBoulard** [comment]
I've updated the repo, and I'm creating an issue on nbio then.

Thank you so much.
