### ISSUE TITLE
Could you make a client auto reconnect example?

### ISSUE THREAD

**Issue by nneesshh** [lesismal/nbio-examples#20]
I just can't find the right onClose callback when the server restart.
I want to auto reconect to server by try reconect  for every 10 seconds.
Thank you very much

**Comment by nneesshh** [comment]
I use the "nbio-examples/websocket/nbioclient/client.go" example, and connect to a ws server.
when the server shutdown, the "
        u.OnClose(func(c *websocket.Conn, err error) {
		fmt.Println("OnClose:", c.RemoteAddr().String(), err)
	})"
doesn't triggered

**Comment by lesismal** [comment]
Thank you for your feedback!
It should be the same as https://github.com/lesismal/nbio/issues/422
I've published a new version, please try the latest:
https://github.com/lesismal/nbio/releases/tag/v1.5.9

**Comment by nneesshh** [comment]
perfect. thank you for your great work
