### ISSUE TITLE
upgrader.OnMessage内消息如果同步处理较慢操作是否会丢包

### ISSUE THREAD

**Issue by liushunshun** [lesismal/nbio-examples#3]
go 小白请教一个问题，upgrader.OnMessage 拿到消息之后，业务代码处理消息是不是也要交给异步协程？如果同步处理是不是也会导致io事件处理慢、read buffer 溢出而丢包呢

**Comment by lesismal** [comment]
> go 小白请教一个问题，upgrader.OnMessage 拿到消息之后，业务代码处理消息是不是也要交给异步协程？

通常不需要再异步的，io/poller是单独的协程池，OnMessage是在另外的逻辑协程池，这个逻辑协程池是size可控的，默认为 ` runtime.NumCPU() * 1024` 个，可以通过设置 `conf.MessageHandlerPoolSize` 来自行定制这个逻辑协程池的 size，也可以通过设置 `conf.ServerExecutor` 来自行定制逻辑协程池 

> 如果同步处理是不是也会导致io事件处理慢、read buffer 溢出而丢包呢

io协程池负责读数据和解析消息，然后传递到逻辑协程池执行。
默认的逻辑协程池带有队列，当已存在的协程数量达到设置的size时，会放入队列中等待其他协程执行完之后再来执行队列中的任务。

存在一些极端情况：比如你的逻辑代码消费太慢，并且有很多client会持续不断高频发消息给server，那么会到导致队列内堆积了大量的消息，这些消息会持续占用内存，如果 `堆积消息数量*每个消息平均占用的内存` 很大会导致进程内存占用巨大，但通常的场景不会这样。如果想避免这种风险，可以定制 `conf.ServerExecutor` 来限制协程数量和队列size，达到阈值时io/poller协程传递消息给逻辑协程池时会阻塞、从而实现逻辑协程池对io/poller协程池的反向流控，这样就能确保进程不至于内存占用过高而OOM。逻辑协程池还可以通过对Conn的限流来关闭那些不健康的Conn（比如这里说到的以超过合理范围的高频率发消息给server的，有可能是攻击）

**Comment by lesismal** [comment]
那些导致阻塞的比如数据库操作，在数据库的driver层也是有连接/协程池的数量限制的，所以nbio逻辑协程池size远大于其他那些可能导致阻塞的基础设施的连接池size的情况下，nbio框架层提供的逻辑协程池是足够并且数量可控的。
当然，如前面所述，nbio已经提供了扩展方式，用户需要的情况下自行定制就好了。

另外，对于每个Conn，虽然io与逻辑协程是分开的，但每个Conn的message是被有序处理的。消息有序这一点跟标准库方案比如gorilla是类似的，你需要一个单独的读协程去循环读取，读到一个就处理一个。如果业务上对每个Conn的不同消息有不同的同步异步要求，应该由业务层自行处理、比如单个Conn某个消息处理的慢但是不想因为这个消息阻塞导致这个Conn其他消息处理慢，那这个消息可以去异步处理

**Comment by liushunshun** [comment]
非常感谢指点，讲的很清楚，逻辑协程池和IO协程池是分开的并且可定制的设计非常好，希望nbio越来越强大稳定 🙏

**Comment by lesismal** [comment]
感谢支持！
