### ISSUE TITLE
Send message to all active connections

### ISSUE THREAD

**Issue by samfrm** [lesismal/nbio-examples#4]
Currently I keep connections in a variable but I need to take care of add or remove indexes: 
```
Clients          = make(map[string]*websocket.Conn)
```

Is there any example of server code that I can send messages to all connections?

**Comment by lesismal** [comment]
> Currently I keep connections in a variable but I need to take care of add or remove indexes:

That should be your responsibility to manage the connections.

Of course, `nbio` can implement a simple manager like yours `map[string]*websocket.Conn`, but that's not effective.
1. Not everyone wants `map[string]*websocket.Conn`, maybe someone wants to optimize performance and then using `map[uintptr]struct{}`(with conversion between uintptr and `websocket.Conn` to avoid pointer in `map` then to avoid `gc` scan).
2. Most of the servers should add a connection after authentication, else the server may waste more to send msg to invalid connections.  

So, even if `nbio` implement a connection manager, most of the users will implement the manager themselves, which makes `nbio`'s implementation just a waste.

Like the relation of [gorilla/websocket](https://github.com/gorilla/websocket) and [melody](https://github.com/olahol/melody), the latter is based on the former. The connection manager should be implemented by users who use `nbio`.

**Comment by samfrm** [comment]
> That should be the user's responsibility to manage the connections.
> 
> Of course, `nbio` can implement a simple manager like your `map[string]*websocket.Conn`, but that's not effective:

> So, even if `nbio` implement a connection manager, most of the users will implement the manager themselves, which makes `nbio`'s implementation just a waste.
> 

I understand that it would be useless for most users since it may change based on users' needs.

I just wonder if nbio keeps those connections somewhere so I can just loop through and send them a message (Broadcast)

my implementation works best with approximately 100 connections but with higher numbers, while removing indexes from the map, it will crash.

I add the connection after authentication and this is how I do it:

```
wsConn := conn.(*websocket.Conn)
err = wsConn.SetReadDeadline(time.Time{})
...
Clients[wsConn.RemoteAddr().String()] = wsConn
```

and in the newUpgrader, in OnClose I do this:
```
u := websocket.NewUpgrader()
u.OnClose(func(c *websocket.Conn, err error) {

	// remove client from the list
	for i, cn := range Clients {
		if cn.Conn.RemoteAddr().String() == c.RemoteAddr().String() {
			delete(Clients, i)
		}
	}

})
```

I am pretty sure that there is better implementation but couldn't find something that works.

**Comment by lesismal** [comment]
There's no public interface to broadcast to all `websocket.Conn` in `nbio`, that would effects performance so I think I won't support it in the future.

For the crash, I would suggest using `sync.Map` or map+`RWMutex/Mutex`.
Because there's a goroutine pool that handles the `OnOpen/OnClose` callbacks. If there are many connections, most of the time, callbacks for different connections will be executed in different goroutines. Concurrent `Read/Write` to a map without lock operations will cause that crash.

**Comment by samfrm** [comment]
> For the crash, I would suggest using `sync.Map` or map+`RWMutex/Mutex`. Because there's a goroutine pool that handles the `OnOpen/OnClose` callbacks. If there are many connections, most of the time, callbacks for different connections will be executed in different goroutines. Concurrent `Read/Write` to a map without lock operations will cause that crash.

Thank you for your help. I think this is the solution so I will go for it.

> There's no public interface to broadcast to all `websocket.Conn` in `nbio`, that would effects performance so I think I won't support it in the future.
> 

Maybe after my code works well, I will create a repo as a complement for nbio supporting this :yum:

**Comment by lesismal** [comment]
> Thank you for your help. I think this is the solution so I will go for it.

You are welcome!

> Maybe after my code works well, I will create a repo as a complement for nbio supporting this 😋

Glad to hear that! Please let me know and get my star when you made it! 😄

**Comment by samfrm** [comment]
> 
> Glad to hear that! When you made it please let me know and get my star for it! smile

Thanks for the positive energy. Then will do my best to have your support and that star :laughing:
