### ISSUE TITLE
websocket_1m_tls client connect exception

### ISSUE THREAD

**Issue by liushunshun** [lesismal/nbio-examples#6]
![image](https://user-images.githubusercontent.com/8638224/191430472-3534fcd3-49ff-4368-a189-3d7e11bf5e37.png)

在websocket_1m_tls 包的 client.go 中增加了异常打印之后，发现有这种 tls: internal error 

 server 端是 nbio websocket tls 

请教一下，这种问题应该如何排查？

**Comment by liushunshun** [comment]
server 端demo : https://github.com/liushunshun/go-live-chat/blob/main/internal/server/websocket_server.go

**Comment by lesismal** [comment]
我查看了下nbio的tls源码，"internal error"的地方基本都是"internal error: reason"的格式，所以你的日志中只带有"internal error"的可能不是nbio的tls产生的，我本地没有复现出这个报错，所以暂时没做进一步尝试。

怀疑可能是标准库产生了这个error一路传递给了应用层，比如并发Dial的时候可能会失败。可以试下减少并发Dial的协程数量，或者去掉pool.Go改成串行Dial再观察下，我的示例代码里的for dial也是为了避免失败就退出了所以重试

另外就是你可以查看下内核参数是否需要优化，比如 tcp_max_syn_backlog, somaxconn

**Comment by liushunshun** [comment]
好的，非常感谢你的回复，谢谢
